export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
};
export const productConstants = {
  GET_PRODUCT_BY_QUERY_REQUEST: "GET_PRODUCT_BY_QUERY_REQUEST",
  GET_PRODUCT_BY_QUERY_SUCCESS: "GET_PRODUCT_BY_QUERY_SUCCESS",
  GET_PRODUCT_BY_QUERY_FAILURE: "GET_PRODUCT_BY_QUERY_FAILURE",
  GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
  GET_PRODUCT_BY_SLUG_SUCCESS: "GET_PRODUCT_BY_SLUG_SUCCESS",
  GET_PRODUCT_BY_SLUG_FAILURE: "GET_PRODUCT_BY_SLUG_FAILURE",
  GET_PAGE_REQUEST: "GET_PAGE_REQUEST",
  GET_PAGE_FAILURE: "GET_PAGE_FAILURE",
  GET_PAGE_SUCCESS: "GET_PAGE_SUCCESS",

  GET_DETAIL_REQUEST: "GET_DETAIL_REQUEST",
  GET_DETAIL_FAILURE: "GET_DETAIL_FAILURE",
  GET_DETAIL_SUCCESS: "GET_DETAIL_SUCCESS",

  GET_PRODUCT1_REQUEST: "GET_PRODUCT1_REQUEST",
  GET_PRODUCT1_FAILURE: "GET_PRODUCT1_FAILURE",
  GET_PRODUCT1_SUCCESS: "GET_PRODUCT1_SUCCESS",

  GET_PRODUCT2_REQUEST: "GET_PRODUCT2_REQUEST",
  GET_PRODUCT2_FAILURE: "GET_PRODUCT2_FAILURE",
  GET_PRODUCT2_SUCCESS: "GET_PRODUCT2_SUCCESS",

  COMMENT_REQUEST: "COMMENT_REQUEST",
  COMMENT_FAILURE: "COMMENT_FAILURE",
  COMMENT_SUCCESS: "COMMENT_SUCCESS",

  GET_COMMENTS_REQUEST: "GET_COMMENTS_REQUEST",
  GET_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
};
export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
  GOOGLE_SIGN_IN_REQUEST: "GOOGLE_SIGN_IN_REQUEST",
  GOOGLE_SIGN_IN_SUCCESS: "GOOGLE_SIGN_IN_SUCCESS",
  GOOGLE_SIGN_IN_FAILURE: "GOOGLE_SIGN_IN_FAILURE",
  SHOW_LOGIN_MODAL: "SHOW_LOGIN_MODAL",
  CLOSE_LOGIN_MODAL: "CLOSE_LOGIN_MODAL",
};
export const cartConstants = {
  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",

  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

  DELETE_CART_ITEM_REQUEST: "DELETE_CART_ITEM_REQUEST",
  DELETE_CART_ITEM_SUCCESS: "DELETE_CART_ITEM_SUCCESS",
  DELETE_CART_ITEM_FAILURE: "DELETE_CART_ITEM_FAILURE",
  RESET_CART: "RESET_CART",
};
export const userConstants = {
  GET_ADDRESS_REQUEST: "GET_ADDRESS_REQUEST",
  GET_ADDRESS_SUCCESS: "GET_ADDRESS_SUCCESS",
  GET_ADDRESS_FAILURE: "GET_ADDRESS_FAILURE",
  ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",
  UPDATE_ADDRESS_REQUEST: "UPDATE_ADDRESS_REQUEST",
  UPDATE_ADDRESS_SUCCESS: "UPDATE_ADDRESS_SUCCESS",
  UPDATE_ADDRESS_FAILURE: "UPDATE_ADDRESS_FAILURE",
  GET_ORDER_REQUEST: "GET_ORDER_REQUEST",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_FAILURE: "GET_ORDER_FAILURE",
  ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST",
  ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
  ADD_ORDER_FAILURE: "ADD_ORDER_FAILURE",
  GET_ORDER_DETAIL_REQUEST: "GET_ORDER_DETAIL_REQUEST",
  GET_ORDER_DETAIL_SUCCESS: "GET_ORDER_DETAIL_SUCCESS",
  GET_ORDER_DETAIL_FAILURE: "GET_ORDER_DETAIL_FAILURE",
  RESET_USER: "RESET_USER",
};

export const labelConstants = {
  GET_ALL_LABEL_REQUEST: "GET_ALL_LABEL_REQUEST",
  GET_ALL_LABEL_FAILURE: "GET_ALL_LABEL_FAILURE",
  GET_ALL_LABEL_SUCCESS: "GET_ALL_LABEL_SUCCESS",

  GET_LABEL_REQUEST: "GET_LABEL_REQUEST",
  GET_LABEL_FAILURE: "GET_LABEL_FAILURE",
  GET_LABEL_SUCCESS: "GET_LABEL_SUCCESS",
};
